# Generated by Django 5.1.2 on 2024-10-23 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluguel',
            old_name='calor',
            new_name='valor',
        ),
    ]
